# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Цена')),
                ('czk', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Цена')),
                ('eur', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Цена')),
                ('pln', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Цена')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
