# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-08 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20180407_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratesdata',
            name='czk',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=5, verbose_name='CZK'),
        ),
        migrations.AlterField(
            model_name='ratesdata',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ratesdata',
            name='eur',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=5, verbose_name='EUR'),
        ),
        migrations.AlterField(
            model_name='ratesdata',
            name='pln',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=5, verbose_name='PLN'),
        ),
        migrations.AlterField(
            model_name='ratesdata',
            name='usd',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=5, verbose_name='USD'),
        ),
    ]
